"""empty message

Revision ID: 4b899d8af750
Revises: e54ea3230784
Create Date: 2022-05-22 23:54:53.378439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b899d8af750'
down_revision = 'e54ea3230784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'time')
    # ### end Alembic commands ###
