"""empty message

Revision ID: 9d51f4979567
Revises: af209ff88866
Create Date: 2022-05-24 13:33:28.720315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d51f4979567'
down_revision = 'af209ff88866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_query', 'query_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_query', 'query_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
